### PR TITLE
Bpod Settings, Calibration Files, and Protocols are saved in the user…

### PR DESCRIPTION
**Pull request by fitzsturgill**
…-specific home directory (e.g. /Users/JoeUser/BpodUser/). This BpodUser directory is created automatically if not found. BpodInputConfig copied to this new directory automatically. Calibration files and protocols and data (if desired) must be copied manually.

I've tested this on PC but not OSX or Unix
!!! Related to #2 and #4

### CODE REVIEW

**Comment by torbencshl** [comment]
Nice, thank you!

I have multiple suggestions

1) Bpod creates (on my win machine) a `BpodSystemSettings.mat` in the `Settings Files` folder. I guess this should also go to `BpodUserPath`

2) When initializing, it might be good to copy at least calibration files and setting files  automatically? To be able to run protocols without manually moving stuff. Data and Protocols possibly, too?

3) Suggestion: make `BpodUserPath `editable (eg a dropbox folder or server). But might need a button in GUI so a little much to change. or create a default settings file containing `BpodUserPath`, which could be manually edited (make `~/BposUser/ `the default when initializing)

**Comment by torbencshl** [comment]
sorry, you're doing 1) already, I got confused because of the emulator mode...

**Comment by fitzsturgill** [comment]
For #2- I think that copying the calibration files and settings files
automatically (besides the BpodSystemSettings file) is a good idea. It's
something that is only relevent when migrating to the new version but still
I'll implement this (unless someone beats me to it :)   basically I think
you just use the code for copying the System Settings.

For #3- I think this is a good idea, too, but a little complex.  What we
are moving to the BpodUser Folder are inherently machine specific settings
and all the code besides these settings will be stored remotely on GitHub.
Being machine specific it kind of makes sense for these to be stored on the
computer itself. Likewise the data since writing over a slow server
connection wouldn't be ideal. I dunno, maybe in the spirit of conservatism
its best to just keep it as close as possible to Josh's code while
fulfilling the goal of having these settings pulled out of the main Bpod
directory....

**Comment by fitzsturgill** [comment]
P.S.- I haven't tested this on Mac.....

**Comment by torbencshl** [comment]
I agree with your point about the server, that's why dropbox is nice. I wouldn't want to manually copy behavior files for a dozen animals each day...Or how do you that? I guess you could have a matlab script copying files to server but even that I would find pretty inconvenient when working with a lot of animals. Unless the script is started automatically, which I would suggest anyway that there is a `customFunction.m` called when behavior is stopped/bpod ended (but that's another less important feature suggestion).

What about an easier solution, which only needs a small change, for which one additional `BpodUserPath.mat `is created in the Bpod home directory` /Settings Files/`, containing only `BpodUserPath`. [Disadvantage: is rig-specific and we wanted to have rig-specific things moved out from Bpod directory, but could use gitignore then it will also not be visible online?. This could be solved by saving this one file somewhere else, but then question is where]. If file does not exist, it is created with `BpodUserPath = ~/BpodUser/`, similar to what you do now (just that it writes a file in addition). If file exists, reads contents (could be `BpodUserPath = ~/BpodUser/` or anything else, to be manually edited by every user on rig independently).

**Comment by torbencshl** [comment]
when I run a protocol, session data is not saved in` BpodUserPath/Data/` but still in `Bpod/Data`

Does anyone experience the same problem?

**Comment by fitzsturgill** [comment]
Searching for "BpodPath" within files across the matlab path reveals that
we have to change BpodPath to BpodUserPath in a bunch more places.....
 oops....
Torben- tried your changes and seem to work fine (at least it copies the
stuff over)

**Comment by fitzsturgill** [comment]
loadBpodPath isn't really used....  so we don't have to change anything
within it

**Comment by tsgouvea** [comment]
I like @torbencshl 's suggestion of having the Bpod User folder in an arbitrary located (as suggested in #2).
In implementing that, It seems reasonable to me to have something like a `Bpod/Settings Files/BpodUserPath.mat`. I think this strategy is pretty common (e.g. Matlab's own `pathdef.m`).

**Comment by tsgouvea** [comment]
If I got it right, the thing with copying folders seems to be a bit too situation-specific to be burned into the code (only useful in this transition, right?). On the other hand, it doesn't harm.

**Comment by fitzsturgill** [comment]
@torbencshl The BpodUserPath branch seems to work fine. I tested it with a simple protocol (head fixed habituation delivering water rewards randomly and recording licks) Maybe you'd like to pull this and add a way to add a custom data folder? (e.g. dropbox?).

**Comment by fitzsturgill** [comment]
@torbencshl The BpodUserPath branch seems to work fine. I tested it with a simple protocol (head fixed habituation delivering water rewards randomly and recording licks) Maybe you'd like to pull this and add a way to add a custom data folder? (e.g. dropbox?).

**Comment by fitzsturgill** [comment]
@torbencshl The BpodUserPath branch seems to work fine. I tested it with a simple protocol (head fixed habituation delivering water rewards randomly and recording licks) Maybe you'd like to pull this and add a way to add a custom data folder? (e.g. dropbox?).

**Comment by fitzsturgill** [comment]
@torbencshl The BpodUserPath branch seems to work fine. I tested it with a simple protocol (head fixed habituation delivering water rewards randomly and recording licks) Maybe you'd like to pull this and add a way to add a custom data folder? (e.g. dropbox?).

**Comment by fitzsturgill** [comment]
@torbencshl The BpodUserPath branch seems to work fine. I tested it with a simple protocol (head fixed habituation delivering water rewards randomly and recording licks) Maybe you'd like to pull this and add a way to add a custom data folder? (e.g. dropbox?).

**Comment by torbencshl** [comment]
great!! quick test seems to work fine.

**Comment by fitzsturgill** [comment]
great- Torben- let's talk tomorrow about implementing the custom folders
thingy- dropbox.  most transparent option would be to just have bpod check
for a hardcoded .m or .mat file that would substitute another path for
bpoduserpath.  however, if you wanted to have just hte data path separate,
it'd  be slightly more work.

**Pull request merged**
